# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7bef69ea94952f2a51157d37625065ff1ce612f6d9525dd472993da1152814f5a2a72eb3e30aa99788be41760d24cfa95a6e5277e0b8da7c7104568e6a3a90c

test:
  secret_key_base: 1f0c6bc4a68abab67481e6cd8d6b2c6359996177829ce657b5a88002253a303661a33729a73d5c858ee4dca89cf395e7f63ad6055daa42926e9f29198eb69b92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
