# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34242f004b6a554a40a441affc9712981003aa5d84b977ae695a9c72f8a0b8e0e9f1058dd0ea1dadfa8acdfffd7e0b4195bdf933404ad9f6544f0000cbb399d7

test:
  secret_key_base: 531ff9d4c0d32f4e156fb82041ccb1f8804954c0fae139f51e447e994a7b4e87ffcd46b0d37e98518b052783afb248afd294c12dc7a53196417fbb45cf8d857f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
